<?php
/**
 * Message translations.
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Trinity TV'                                         => 'Тринити ТВ',
	'Contract Partner'                                   => 'Договор Партнера',
	'Tariff'                                             => 'Тариф',
	'Tariff Price'                                       => 'Цена тарифа',
	'Contract Trinity'                                   => 'Договор Тринити',
	'Devices Count'                                      => 'Устройства',
	'Contract Date'                                      => 'Дата создания',
	'No device'                                          => 'Без устройств',
	'One device'                                         => 'Одно устройство',
	'Two devices'                                        => 'Два устройства',
	'Three devices'                                      => 'Три Устройства',
	'Four devices'                                       => 'Четыре устройства',
	'Active'                                             => 'Активный',
	'Block'                                              => 'Заблокирован',
	'Rows per page'                                      => 'Записей на страницу',
	'State'                                              => 'Состояние',
	'Select item...'                                     => 'Выберите из списка...',
	'First Name'                                         => 'Имя',
	'Last Name'                                          => 'Фамилия',
	'Middle Name'                                        => 'Отчество',
	'Address'                                            => 'Адресс',
	'Actions'                                            => 'Действия',
	'At least 1 of the field must be filled up properly' => 'Как минимум 1 поле должно быть заполнено правильно',
	'Add Device'                                         => 'Добавить устройство',
	'Change User Info'                                   => 'Изменить данные пользователя',
	'Add Device by Code'                                 => 'Добавить устройство по коду',
	'Change Tariff'                                      => 'Изменить тариф',
	'Enable/Disable'                                     => 'Включить/Выключить',
	'Action success!'                                    => 'Изменение выполнено успешно',
	'Error! '                                            => 'Ошибка! ',
	'Debug'                                              => 'Отладка',
	'No valid MAC-address'                               => 'Не валидный мак-адрес',
	'Tariff Name'                                        => 'Тариф',
	'State Name'                                         => 'Состояние',
	'Devices'                                            => 'Устройства',
	'Device List'                                        => 'Список устройств',
	'Show Full User Info'                                => 'Полная информация по пользователю',
	'Add Playlist'                                       => 'Добавить плэйлист',
	'Playlist'                                           => 'Плэйлист',
	'Balance'                                            => 'Баланс',
	'Note'                                               => 'Заметки',
	'Last Session Date'                                  => 'Последняя активность',
];
